# Generated by Django 5.2.4 on 2025-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                default="admin",
                help_text="Slug",
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
    ]
