# Generated by Django 5.2.4 on 2025-09-25 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_content"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bookmarked_articles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Articles bookmarked by user",
                related_name="bookmarked_by",
                to="articles.article",
                verbose_name="bookmarked articles",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users following this user",
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="followers",
            ),
        ),
    ]
