# Generated by Django 5.2.4 on 2025-08-19 07:44

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="Tell us about yourself",
                max_length=256,
                null=True,
                verbose_name="bio",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="User country",
                max_length=2,
                null=True,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="User phone number",
                max_length=128,
                null=True,
                region=None,
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Profile image",
                null=True,
                upload_to="images/users/",
                verbose_name="image",
            ),
        ),
    ]
