# Generated by Django 5.2.6 on 2025-09-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_bookmarked_articles_user_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Letters, numbers and dash only",
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
