# Generated by Django 5.2.3 on 2025-07-01 06:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "description",
                    wagtail.fields.StreamField(
                        [
                            ("quote", 0),
                            ("paragraph", 1),
                            ("table", 2),
                            ("table_typed", 8),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"help_text": "Quote"},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Paragraph"},
                            ),
                            2: (
                                "wagtail.contrib.table_block.blocks.TableBlock",
                                (),
                                {"help_text": "Table"},
                            ),
                            3: ("wagtail.blocks.CharBlock", (), {}),
                            4: ("wagtail.blocks.FloatBlock", (), {}),
                            5: ("wagtail.blocks.RichTextBlock", (), {}),
                            6: ("wagtail.images.blocks.ImageBlock", [], {}),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("be", "Belgium"),
                                        ("fr", "France"),
                                        ("de", "Germany"),
                                        ("nl", "Netherlands"),
                                        ("pl", "Poland"),
                                        ("uk", "United Kingdom"),
                                    ]
                                },
                            ),
                            8: (
                                "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                                [
                                    [
                                        ("text", 3),
                                        ("numeric", 4),
                                        ("rich_text", 5),
                                        ("image", 6),
                                        ("country", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Category description",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
