# Generated by Django 5.2.4 on 2025-08-18 06:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Category description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="categoryindex",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Page description", null=True
            ),
        ),
    ]
