# Generated by Django 5.2.4 on 2025-08-19 07:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="categoryindex",
            options={
                "verbose_name": "Category index page",
                "verbose_name_plural": "Category index pages",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Category description",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="display_owner",
            field=models.BooleanField(
                default=False,
                help_text="Wether to display the name of the owner of news article",
                verbose_name="show owner",
            ),
        ),
        migrations.AlterField(
            model_name="categoryindex",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Page description",
                null=True,
                verbose_name="description",
            ),
        ),
    ]
