# Generated by Django 5.1.7 on 2025-04-18 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Designates if the abuse report is correct",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        db_index=True,
                        help_text="Message that will help us understand and handle the situation",
                        max_length=256,
                    ),
                ),
                (
                    "reason",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Rude or vulgar"),
                            (1, "Harassment or hate speech"),
                            (2, "Spam"),
                            (3, "Copy right issue"),
                            (4, "Inappropriate"),
                            (5, "Other"),
                        ],
                        db_index=True,
                        default=0,
                        help_text="Report reason",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date published"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Reported Article",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
            ],
        ),
    ]
