# Generated by Django 5.2.4 on 2025-08-22 08:29

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Country",
                max_length=2,
                null=True,
                verbose_name="country",
            ),
        ),
    ]
