# Generated by Django 5.2.4 on 2025-08-19 07:44

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("tags", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "verbose_name": "News article",
                "verbose_name_plural": "News articles",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 3),
                    ("document", 4),
                ],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    2: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                help_text="Article content",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="headline",
            field=models.CharField(
                db_index=True,
                help_text="Article headline",
                max_length=256,
                verbose_name="headline",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ForeignKey(
                help_text="Article image",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_breaking",
            field=models.BooleanField(
                default=False,
                help_text="Designates if the Article is in breaking news",
                verbose_name="is breaking",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="recommendations",
            field=models.ManyToManyField(
                help_text="recommendations",
                to="articles.article",
                verbose_name="Similar articles",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Tags",
                through="tags.ArticleTag",
                to="taggit.Tag",
                verbose_name="tags",
            ),
        ),
    ]
