# Generated by Django 5.2.4 on 2025-09-13 06:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_article_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 3),
                    ("document", 4),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"help_text": "Quote", "verbose_name": "quote"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich Text", "verbose_name": "paragraph"},
                    ),
                    2: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "verbose_name": "video"},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image", "verbose_name": "image"},
                    ),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document", "verbose_name": "document"},
                    ),
                },
                help_text="Article content",
                verbose_name="content",
            ),
        ),
    ]
