# Generated by Django 5.2.4 on 2025-08-19 15:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import tcn.apps.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update",
                        verbose_name="Last update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date created",
                        verbose_name="Date created",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog index page",
                "abstract": False,
            },
            bases=(
                tcn.apps.mixins.ChildPaginatorMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update",
                        verbose_name="Last update",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        db_index=True,
                        help_text="Post headline",
                        max_length=128,
                        verbose_name="headline",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("quote", 0),
                            ("paragraph", 1),
                            ("video", 2),
                            ("image", 3),
                            ("document", 4),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"help_text": "Quote"},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich Text"},
                            ),
                            2: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video"},
                            ),
                            3: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image"},
                            ),
                            4: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"help_text": "Document"},
                            ),
                        },
                        help_text="Post content",
                        verbose_name="content",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Post image",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtailimages.image",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog post",
                "verbose_name_plural": "Blog posts",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
