# Generated by Django 5.2.4 on 2025-08-17 09:12

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Post tags",
                through="tags.PostTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
