# Generated by Django 5.2.4 on 2025-08-19 07:44

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("tags", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Blog post", "verbose_name_plural": "Blog posts"},
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 3),
                    ("document", 4),
                ],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    2: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                help_text="Post content",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="headline",
            field=models.CharField(
                db_index=True,
                help_text="Post headline",
                max_length=128,
                verbose_name="headline",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ForeignKey(
                help_text="Post image",
                on_delete=django.db.models.deletion.PROTECT,
                to="wagtailimages.image",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Post tags",
                through="tags.PostTag",
                to="taggit.Tag",
                verbose_name="tags",
            ),
        ),
    ]
