# Generated by Django 5.2.4 on 2025-08-19 07:44

import django.db.models.deletion
import tcn.apps.links.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0003_alter_article_options_alter_article_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=tcn.apps.links.models.create_slug,
                        help_text="slug",
                        max_length=16,
                        unique=True,
                        verbose_name="Link url",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        help_text="article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link",
                        to="articles.article",
                        verbose_name="Related article",
                    ),
                ),
                (
                    "views",
                    models.ManyToManyField(
                        help_text="views",
                        related_name="views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Article views",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
            },
        ),
    ]
