# Generated by Django 5.2.4 on 2025-08-19 15:29

import django.db.models.deletion
from django.db import migrations, models

import tcn.apps.links.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=tcn.apps.links.models.create_slug,
                        help_text="slug",
                        max_length=16,
                        unique=True,
                        verbose_name="Link url",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        help_text="article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link",
                        to="articles.article",
                        verbose_name="Related article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
            },
        ),
    ]
