# Generated by Django 5.2.4 on 2025-08-19 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("links", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="views",
            field=models.ManyToManyField(
                help_text="views",
                related_name="views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Article views",
            ),
        ),
    ]
