# Generated by Django 5.2.4 on 2025-08-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="views", verbose_name="Article views"
            ),
        ),
    ]
