# Generated by Django 5.1.7 on 2025-04-18 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Article Photo",
                        null=True,
                        upload_to="al_yaqeen/images/articles/",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Article title", max_length=64
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        db_index=True, help_text="Article headline", max_length=256
                    ),
                ),
                (
                    "extras",
                    models.JSONField(
                        blank=True,
                        help_text="Article extra data like summary etc...",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(db_index=True, help_text="Article content"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Designates if the Article is pinned"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date published"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Article category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
