# Generated by Django 5.1.7 on 2025-04-18 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        ("comments", "0001_initial"),
        ("reactions", "0001_initial"),
        ("reports", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments",
            field=models.ManyToManyField(
                help_text="Article comments",
                related_name="comments",
                through="comments.Comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reactions",
            field=models.ManyToManyField(
                help_text="Article reactions",
                related_name="reactions",
                through="reactions.Reaction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="recommendations",
            field=models.ManyToManyField(
                help_text="Similar articles", to="articles.article"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reports",
            field=models.ManyToManyField(
                help_text="Article reports",
                related_name="reports",
                through="reports.Report",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="stargazers",
            field=models.ManyToManyField(
                help_text="Article stargazers",
                related_name="stargazers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Article tags",
                related_name="articles",
                to="tags.tag",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                help_text="Article owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
