# Generated by Django 5.2 on 2025-06-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "emoji",
                    models.CharField(
                        choices=[
                            ("👍🏻", "👍🏻 Like"),
                            ("❤️", "❤️ Love"),
                            ("🤣", "🤣 Funny"),
                            ("😲", "😲 Wow"),
                            ("🤔", "🤔 Thinking"),
                            ("😡", "😡 Angry"),
                        ],
                        default="👍🏻",
                        help_text="Reaction",
                        max_length=8,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Article",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "article"), name="unique_reaction"
                    )
                ],
            },
        ),
    ]
