# Generated by Django 5.1.7 on 2025-04-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Tag Name", max_length=32, unique=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        db_index=True, help_text="Tag color", max_length=8, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_index=True, help_text="Tag Description", max_length=256
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
            ],
        ),
    ]
