# Generated by Django 5.2.4 on 2025-08-19 07:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_about_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={
                "verbose_name": "About page",
                "verbose_name_plural": "About pages",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "verbose_name": "Contact page",
                "verbose_name_plural": "Contact pages",
            },
        ),
        migrations.AlterModelOptions(
            name="home",
            options={"verbose_name": "Home page", "verbose_name_plural": "Home pages"},
        ),
        migrations.AlterField(
            model_name="about",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 3),
                    ("document", 4),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    2: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                help_text="Page content",
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 3),
                    ("document", 4),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    2: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                help_text="Page content",
                null=True,
                verbose_name="content",
            ),
        ),
    ]
