# Generated by Django 5.2.4 on 2025-09-13 07:10

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_about_contact_alter_home_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="from_address",
            field=models.EmailField(
                blank=True, max_length=255, verbose_name="from address"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="message",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Message to display after form submission",
                null=True,
                verbose_name="message",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=255, verbose_name="subject"),
        ),
        migrations.AddField(
            model_name="contact",
            name="to_address",
            field=models.CharField(
                blank=True,
                help_text="Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.",
                max_length=255,
                validators=[wagtail.contrib.forms.models.validate_to_address],
                verbose_name="to address",
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 3),
                    ("document", 4),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"help_text": "Quote", "verbose_name": "quote"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich Text", "verbose_name": "paragraph"},
                    ),
                    2: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "verbose_name": "video"},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image", "verbose_name": "image"},
                    ),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document", "verbose_name": "document"},
                    ),
                },
                help_text="Page content",
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 3),
                    ("document", 4),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"help_text": "Quote", "verbose_name": "quote"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich Text", "verbose_name": "paragraph"},
                    ),
                    2: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "verbose_name": "video"},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image", "verbose_name": "image"},
                    ),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document", "verbose_name": "document"},
                    ),
                },
                help_text="Page content",
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "clean_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Safe name of the form field, the label converted to ascii_snake_case",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label of the form field",
                        max_length=255,
                        verbose_name="label",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("singleline", "Single line text"),
                            ("multiline", "Multi-line text"),
                            ("email", "Email"),
                            ("number", "Number"),
                            ("url", "URL"),
                            ("checkbox", "Checkbox"),
                            ("checkboxes", "Checkboxes"),
                            ("dropdown", "Drop down"),
                            ("multiselect", "Multiple select"),
                            ("radio", "Radio buttons"),
                            ("date", "Date"),
                            ("datetime", "Date/time"),
                            ("hidden", "Hidden field"),
                        ],
                        max_length=16,
                        verbose_name="field type",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="required"),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.",
                        verbose_name="choices",
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True,
                        help_text="Default value. Comma or new line separated values supported for checkboxes.",
                        verbose_name="default value",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="help text"
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="home.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
