# Generated by Django 5.2.6 on 2025-09-29 06:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_about_content_alter_contact_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("alert", 12),
                    ("accordion", 20),
                    ("quote", 21),
                    ("paragraph", 22),
                    ("timeline", 30),
                    ("steps", 36),
                    ("list", 45),
                    ("tabs", 67),
                    ("video", 68),
                    ("image", 69),
                    ("carousel", 75),
                    ("diff", 78),
                    ("document", 79),
                    ("hover_gallery", 82),
                    ("browser_mockup", 86),
                    ("phone_mockup", 89),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "alert-triangle",
                            "help_text": "Icon name (lucide icons)",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if alert is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("soft", "Soft"),
                                ("outline", "Outline"),
                                ("dash", "Dash"),
                            ],
                            "help_text": "Alert style",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("success", "Success"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Alert level",
                        },
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "code",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "help_text": "Alert message",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "check-circle2",
                            "help_text": "Icon name (lucide icons)",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Action label",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Action internal link", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Action external link", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                                ("success", "Success"),
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Action button color",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 5),
                                ("label", 6),
                                ("page", 7),
                                ("url", 8),
                                ("color", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"help_text": "Alert actions", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 0),
                                ("is_vertical", 1),
                                ("style", 2),
                                ("level", 3),
                                ("message", 4),
                                ("actions", 11),
                            ]
                        ],
                        {"help_text": "Alert", "verbose_name": "alert"},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accordion name",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("plus", "Plus"), ("arrow", "Arrow")],
                            "help_text": "Accordion style",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Wether to show or hide item content",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Item title", "max_length": 64, "required": True},
                    ),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Item content", "required": True},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 5),
                                ("is_expanded", 15),
                                ("title", 16),
                                ("content", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"help_text": "Accordion items", "required": True},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 13), ("style", 14), ("items", 19)]],
                        {"help_text": "Accordion", "verbose_name": "accordion"},
                    ),
                    21: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"help_text": "Quote", "verbose_name": "quote"},
                    ),
                    22: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich Text", "verbose_name": "paragraph"},
                    ),
                    23: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if timeline is compact",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if timeline is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if dates should snap to icons",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Item date", "required": True},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Item content",
                            "max_length": 128,
                            "required": True,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("date", 26), ("icon", 5), ("content", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ListBlock",
                        (28,),
                        {"help_text": "Timeline items", "required": True},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("is_compact", 23),
                                ("is_vertical", 24),
                                ("snap_to_icon", 25),
                                ("items", 29),
                            ]
                        ],
                        {"help_text": "Timeline", "verbose_name": "timeline"},
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if Steps is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Item name", "max_length": 64, "required": True},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                                ("success", "Success"),
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Item color",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 32), ("icon", 5), ("color", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {"help_text": "Steps items", "required": True},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("is_vertical", 31), ("items", 35)]],
                        {"help_text": "Steps", "verbose_name": "steps"},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "List title", "max_length": 64, "required": True},
                    ),
                    38: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Item image"},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Item description",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Item internal link", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Item external link", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"help_text": "Actions", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 38),
                                ("title", 16),
                                ("description", 39),
                                ("page", 40),
                                ("url", 41),
                                ("actions", 42),
                            ]
                        ],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {"help_text": "List items", "required": True},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 37), ("items", 44)]],
                        {"help_text": "List", "verbose_name": "list"},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tab name", "max_length": 64, "required": True},
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if tab buttons position is reversed",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("border", "Border"),
                                ("box", "Box"),
                                ("lift", "Lift"),
                            ],
                            "help_text": "Tab style",
                        },
                    ),
                    49: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if tab is selected",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 0),
                                ("is_vertical", 1),
                                ("style", 2),
                                ("level", 3),
                                ("message", 4),
                                ("actions", 11),
                            ]
                        ],
                        {"help_text": "Alert", "required": True},
                    ),
                    51: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide which programming language is used",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide copy buttons",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide window buttons",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Untitled",
                            "help_text": "File name",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Auto"),
                                ("bash", "Bash"),
                                ("c", "C"),
                                ("cpp", "C++"),
                                ("csharp", "C#"),
                                ("css", "CSS"),
                                ("dart", "Dart"),
                                ("dockerfile", "Dockerfile"),
                                ("go", "Go"),
                                ("html", "HTML"),
                                ("java", "Java"),
                                ("javascript", "JavaScript"),
                                ("json", "JSON"),
                                ("kotlin", "Kotlin"),
                                ("lua", "Lua"),
                                ("markdown", "Markdown"),
                                ("php", "PHP"),
                                ("python", "Python"),
                                ("ruby", "Ruby"),
                                ("rust", "Rust"),
                                ("scss", "SCSS"),
                                ("shell", "Shell"),
                                ("sql", "SQL"),
                                ("swift", "Swift"),
                                ("typescript", "TypeScript"),
                                ("xml", "XML"),
                                ("yaml", "YAML"),
                                ("plaintext", "Plain text"),
                            ],
                            "help_text": "Programming language",
                        },
                    ),
                    56: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Code content", "required": True},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("show_language", 51),
                                ("show_copy_btn", 52),
                                ("show_window_btns", 53),
                                ("file_name", 54),
                                ("language", 55),
                                ("code", 56),
                            ]
                        ],
                        {"help_text": "Code", "required": True},
                    ),
                    58: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image"},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image attribution",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 58), ("caption", 59), ("attribution", 60)]],
                        {"help_text": "Image", "required": True},
                    ),
                    62: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "required": True},
                    ),
                    63: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich text", "required": True},
                    ),
                    64: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("alert", 50),
                                ("code", 57),
                                ("image", 61),
                                ("video", 62),
                                ("text", 63),
                            ]
                        ],
                        {"help_text": "Tab Content", "required": True},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("is_selected", 49), ("content", 64)]],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.ListBlock",
                        (65,),
                        {"help_text": "Tab items", "required": True},
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 46),
                                ("is_reversed", 47),
                                ("style", 48),
                                ("items", 66),
                            ]
                        ],
                        {"help_text": "Tabs", "verbose_name": "tabs"},
                    ),
                    68: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "verbose_name": "video"},
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 58), ("caption", 59), ("attribution", 60)]],
                        {"help_text": "Image", "verbose_name": "image"},
                    ),
                    70: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if carousel is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "required": False},
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Caption", "max_length": 128, "required": False},
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 58), ("video", 71), ("caption", 72)]],
                        {},
                    ),
                    74: (
                        "wagtail.blocks.ListBlock",
                        (73,),
                        {"help_text": "Carousel items", "required": True},
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("is_vertical", 70), ("items", 74)]],
                        {"help_text": "Carousel", "verbose_name": "carousel"},
                    ),
                    76: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Diff Item 1"},
                    ),
                    77: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Diff Item 2"},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("item_1", 76), ("item_2", 77)]],
                        {
                            "help_text": "Diff (To compare 2 images)",
                            "verbose_name": "diff",
                        },
                    ),
                    79: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document", "verbose_name": "document"},
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 58), ("caption", 72)]],
                        {},
                    ),
                    81: (
                        "wagtail.blocks.ListBlock",
                        (80,),
                        {"help_text": "Gallery items", "required": True},
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 81)]],
                        {"help_text": "Hover gallery", "verbose_name": "hover gallery"},
                    ),
                    83: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide toolbar",
                            "required": False,
                        },
                    ),
                    84: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Browser URL", "required": True},
                    ),
                    85: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Browser wallpaper"},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("show_url", 83), ("url", 84), ("wallpaper", 85)]],
                        {
                            "help_text": "Browser mockup",
                            "verbose_name": "browser mockup",
                        },
                    ),
                    87: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide camera",
                            "required": False,
                        },
                    ),
                    88: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Phone wallpaper"},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("show_camera", 87), ("wallpaper", 88)]],
                        {"help_text": "Phone mockup", "verbose_name": "phone mockup"},
                    ),
                },
                help_text="Page content",
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("alert", 12),
                    ("accordion", 20),
                    ("quote", 21),
                    ("paragraph", 22),
                    ("timeline", 30),
                    ("steps", 36),
                    ("list", 45),
                    ("tabs", 67),
                    ("video", 68),
                    ("image", 69),
                    ("carousel", 75),
                    ("diff", 78),
                    ("document", 79),
                    ("hover_gallery", 82),
                    ("browser_mockup", 86),
                    ("phone_mockup", 89),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "alert-triangle",
                            "help_text": "Icon name (lucide icons)",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if alert is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("soft", "Soft"),
                                ("outline", "Outline"),
                                ("dash", "Dash"),
                            ],
                            "help_text": "Alert style",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("success", "Success"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Alert level",
                        },
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "code",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "help_text": "Alert message",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "check-circle2",
                            "help_text": "Icon name (lucide icons)",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Action label",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Action internal link", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Action external link", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                                ("success", "Success"),
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Action button color",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 5),
                                ("label", 6),
                                ("page", 7),
                                ("url", 8),
                                ("color", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"help_text": "Alert actions", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 0),
                                ("is_vertical", 1),
                                ("style", 2),
                                ("level", 3),
                                ("message", 4),
                                ("actions", 11),
                            ]
                        ],
                        {"help_text": "Alert", "verbose_name": "alert"},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accordion name",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("plus", "Plus"), ("arrow", "Arrow")],
                            "help_text": "Accordion style",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Wether to show or hide item content",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Item title", "max_length": 64, "required": True},
                    ),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Item content", "required": True},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 5),
                                ("is_expanded", 15),
                                ("title", 16),
                                ("content", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"help_text": "Accordion items", "required": True},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 13), ("style", 14), ("items", 19)]],
                        {"help_text": "Accordion", "verbose_name": "accordion"},
                    ),
                    21: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"help_text": "Quote", "verbose_name": "quote"},
                    ),
                    22: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich Text", "verbose_name": "paragraph"},
                    ),
                    23: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if timeline is compact",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if timeline is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if dates should snap to icons",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Item date", "required": True},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Item content",
                            "max_length": 128,
                            "required": True,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("date", 26), ("icon", 5), ("content", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ListBlock",
                        (28,),
                        {"help_text": "Timeline items", "required": True},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("is_compact", 23),
                                ("is_vertical", 24),
                                ("snap_to_icon", 25),
                                ("items", 29),
                            ]
                        ],
                        {"help_text": "Timeline", "verbose_name": "timeline"},
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if Steps is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Item name", "max_length": 64, "required": True},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                                ("success", "Success"),
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Item color",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 32), ("icon", 5), ("color", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {"help_text": "Steps items", "required": True},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("is_vertical", 31), ("items", 35)]],
                        {"help_text": "Steps", "verbose_name": "steps"},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "List title", "max_length": 64, "required": True},
                    ),
                    38: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Item image"},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Item description",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Item internal link", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Item external link", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"help_text": "Actions", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 38),
                                ("title", 16),
                                ("description", 39),
                                ("page", 40),
                                ("url", 41),
                                ("actions", 42),
                            ]
                        ],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {"help_text": "List items", "required": True},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 37), ("items", 44)]],
                        {"help_text": "List", "verbose_name": "list"},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tab name", "max_length": 64, "required": True},
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if tab buttons position is reversed",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("border", "Border"),
                                ("box", "Box"),
                                ("lift", "Lift"),
                            ],
                            "help_text": "Tab style",
                        },
                    ),
                    49: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if tab is selected",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 0),
                                ("is_vertical", 1),
                                ("style", 2),
                                ("level", 3),
                                ("message", 4),
                                ("actions", 11),
                            ]
                        ],
                        {"help_text": "Alert", "required": True},
                    ),
                    51: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide which programming language is used",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide copy buttons",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide window buttons",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Untitled",
                            "help_text": "File name",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Auto"),
                                ("bash", "Bash"),
                                ("c", "C"),
                                ("cpp", "C++"),
                                ("csharp", "C#"),
                                ("css", "CSS"),
                                ("dart", "Dart"),
                                ("dockerfile", "Dockerfile"),
                                ("go", "Go"),
                                ("html", "HTML"),
                                ("java", "Java"),
                                ("javascript", "JavaScript"),
                                ("json", "JSON"),
                                ("kotlin", "Kotlin"),
                                ("lua", "Lua"),
                                ("markdown", "Markdown"),
                                ("php", "PHP"),
                                ("python", "Python"),
                                ("ruby", "Ruby"),
                                ("rust", "Rust"),
                                ("scss", "SCSS"),
                                ("shell", "Shell"),
                                ("sql", "SQL"),
                                ("swift", "Swift"),
                                ("typescript", "TypeScript"),
                                ("xml", "XML"),
                                ("yaml", "YAML"),
                                ("plaintext", "Plain text"),
                            ],
                            "help_text": "Programming language",
                        },
                    ),
                    56: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Code content", "required": True},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("show_language", 51),
                                ("show_copy_btn", 52),
                                ("show_window_btns", 53),
                                ("file_name", 54),
                                ("language", 55),
                                ("code", 56),
                            ]
                        ],
                        {"help_text": "Code", "required": True},
                    ),
                    58: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image"},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image attribution",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 58), ("caption", 59), ("attribution", 60)]],
                        {"help_text": "Image", "required": True},
                    ),
                    62: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "required": True},
                    ),
                    63: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich text", "required": True},
                    ),
                    64: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("alert", 50),
                                ("code", 57),
                                ("image", 61),
                                ("video", 62),
                                ("text", 63),
                            ]
                        ],
                        {"help_text": "Tab Content", "required": True},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("is_selected", 49), ("content", 64)]],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.ListBlock",
                        (65,),
                        {"help_text": "Tab items", "required": True},
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 46),
                                ("is_reversed", 47),
                                ("style", 48),
                                ("items", 66),
                            ]
                        ],
                        {"help_text": "Tabs", "verbose_name": "tabs"},
                    ),
                    68: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "verbose_name": "video"},
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 58), ("caption", 59), ("attribution", 60)]],
                        {"help_text": "Image", "verbose_name": "image"},
                    ),
                    70: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if carousel is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "required": False},
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Caption", "max_length": 128, "required": False},
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 58), ("video", 71), ("caption", 72)]],
                        {},
                    ),
                    74: (
                        "wagtail.blocks.ListBlock",
                        (73,),
                        {"help_text": "Carousel items", "required": True},
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("is_vertical", 70), ("items", 74)]],
                        {"help_text": "Carousel", "verbose_name": "carousel"},
                    ),
                    76: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Diff Item 1"},
                    ),
                    77: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Diff Item 2"},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("item_1", 76), ("item_2", 77)]],
                        {
                            "help_text": "Diff (To compare 2 images)",
                            "verbose_name": "diff",
                        },
                    ),
                    79: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document", "verbose_name": "document"},
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 58), ("caption", 72)]],
                        {},
                    ),
                    81: (
                        "wagtail.blocks.ListBlock",
                        (80,),
                        {"help_text": "Gallery items", "required": True},
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 81)]],
                        {"help_text": "Hover gallery", "verbose_name": "hover gallery"},
                    ),
                    83: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide toolbar",
                            "required": False,
                        },
                    ),
                    84: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Browser URL", "required": True},
                    ),
                    85: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Browser wallpaper"},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("show_url", 83), ("url", 84), ("wallpaper", 85)]],
                        {
                            "help_text": "Browser mockup",
                            "verbose_name": "browser mockup",
                        },
                    ),
                    87: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide camera",
                            "required": False,
                        },
                    ),
                    88: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Phone wallpaper"},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("show_camera", 87), ("wallpaper", 88)]],
                        {"help_text": "Phone mockup", "verbose_name": "phone mockup"},
                    ),
                },
                help_text="Page content",
                null=True,
                verbose_name="content",
            ),
        ),
    ]
