# Generated by Django 5.2.6 on 2025-10-13 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_detailpages_formdetailpage_home_footer_formfields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="formfield",
            name="page",
        ),
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
    ]
