# Generated by Django 5.2 on 2025-06-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved",
            field=models.ManyToManyField(
                blank=True, help_text="Saved news articles", to="articles.article"
            ),
        ),
    ]
