# Generated by Django 5.1.7 on 2025-04-18 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(db_index=True, help_text="Content")),
                (
                    "extras",
                    models.JSONField(
                        blank=True,
                        help_text="Comment extra data like summary etc...",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date published"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Commented Article",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
                (
                    "replies",
                    models.ManyToManyField(
                        help_text="Comment Replies", to="comments.comment"
                    ),
                ),
            ],
        ),
    ]
