name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run checks
        run: |
          source .venv/bin/activate
          python manage.py check
          python manage.py migrate
          python manage.py test --parallel

      - name: Run test
        run: |
          source .venv/bin/activate
          python manage.py test --parallel
